name: "integrationtests"

on:
  push:
    branches:
      - release-**
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - release-**
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-matrix:
    runs-on: ubuntu-20.04
    steps:
      - id: set-matrix
        run: |
          echo "github.event_name is ${{github.event_name}}"
          echo "GITHUB_REF_NAME is ${GITHUB_REF_NAME}"
          if [[ "${{github.event_name}}" == "schedule" || "${{github.event_name}}" == "workflow_dispatch"  ]]; then
            echo 'meta_matrix=["sqlite3", "redis", "mysql", "tikv", "tidb", "postgres", "badger", "mariadb", "fdb"]' >> $GITHUB_OUTPUT
          elif [[ "${{github.event_name}}" == "pull_request" ||  "${{github.event_name}}" == "push" ]]; then
            echo 'meta_matrix=["redis", "mysql", "tikv"]' >> $GITHUB_OUTPUT
          else
            echo "event_name is not supported" && exit 1
          fi
    outputs:
      meta_matrix: ${{ steps.set-matrix.outputs.meta_matrix }}

  integrationtests:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        meta: ${{ fromJson(needs.build-matrix.outputs.meta_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      
      - name: Set Variable
        id: vars
        run: |
          if [ "${{matrix.meta}}" == "fdb" ]; then
            echo "target=juicefs.fdb" >> $GITHUB_OUTPUT
          else
            echo "target=juicefs" >> $GITHUB_OUTPUT
          fi

      - name: Build
        uses: ./.github/actions/build
        with: 
          target: ${{steps.vars.outputs.target}}

      - name: Prepare meta db
        run: | 
          chmod +x .github/scripts/start_meta_engine.sh
          source .github/scripts/start_meta_engine.sh
          start_meta_engine ${{matrix.meta}}
          meta_url=$(get_meta_url ${{matrix.meta}})
          create_database $meta_url

      - name: Juicefs Format
        run: |
          source .github/scripts/start_meta_engine.sh
          meta_url=$(get_meta_url ${{matrix.meta}})
          sudo ./juicefs format $meta_url --trash-days 0 pics
      
      - name: Juicefs Mount
        run: |
          source .github/scripts/start_meta_engine.sh
          meta_url=$(get_meta_url ${{matrix.meta}})
          sudo ./juicefs mount -d $meta_url /jfs --no-usage-report --enable-xattr
          stat /jfs/.accesslog

      - name: Fslock Test
        run: |
          cd /jfs/
          git clone https://github.com/danjacques/gofslock.git
          cd gofslock && git checkout cc7f001fe0e7df1710adc8f0cd9e9d6d21fdb3a9
          go test -v ./fslock/...
          stat /jfs/

      - name: Pyxattr Test
        run: |
          git clone https://github.com/iustin/pyxattr.git
          cd pyxattr
          pip3 install pytest
          pip3 install pyxattr
          stat /jfs/
          TEST_DIR=/jfs/ python3 -m pytest tests


      - name: Fstests
        run: |
          sudo .github/scripts/apt_install.sh  libacl1-dev attr
          sudo DURATION=60 make -C fstests fsx
          sudo make -C fstests xattrs
          sudo make -C fstests flock
      
      - name: make secfs.test
        run: |
          sudo .github/scripts/apt_install.sh  libacl1-dev
          git clone https://github.com/billziss-gh/secfs.test.git
          make -C secfs.test
  
      - name: Fsx Test
        timeout-minutes: 16
        run: |
          if [[ "${{github.event_name}}" == "schedule" || "${{github.event_name}}" == "workflow_dispatch"  ]] ; then
            duration=900
          else
            duration=300
          fi
          sudo touch /jfs/fsx.out
          sudo rm -f /tmp/fsx.out
          sudo ln -s /jfs/fsx.out /tmp/fsx.out
          sudo secfs.test/tools/bin/fsx -d $duration -p 10000 -F 10000000 /tmp/fsx.out
      
      - name: Fsracer
        #https://github.com/gfx/example-github-actions-with-tty
        shell: 'script -q -e -c "bash {0}"'
        run: |
          sudo DURATION=60 make -C fstests fsracer


      - name: log
        if: ${{ always() }}
        run: |
          tail -300 /var/log/juicefs.log
          grep "<FATAL>:" /var/log/juicefs.log && exit 1 || true

      - name: Send Slack Notification
        if: ${{ failure() }}
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"


      - name: Setup upterm session
        if: ${{ failure()  && github.event.inputs.debug == 'true' }}
        timeout-minutes: 60
        uses: lhotari/action-upterm@v1
